stream_over_http_enabled: true
server:
    http_listen_port: 3200

distributor:
    receivers:
        otlp:
            protocols:
                grpc:
                    endpoint: 0.0.0.0:4317
                http:
                    endpoint: 0.0.0.0:4318
        zipkin:

storage:
    trace:
        backend: local
        local:
            path: /tmp/tempo/traces
        wal:
            path: /tmp/tempo/wal

compactor:
    compaction:
        block_retention: 48h

metrics_generator:
    registry:
        external_labels:
            source: tempo
            cluster: docker-compose
    storage:
        path: /tmp/tempo/generator/wal
        remote_write:
            - url: http://prometheus:9090/api/v1/write
              send_exemplars: true

overrides:
    defaults:
        metrics_generator:
            processors: [service-graphs, span-metrics, local-blocks] # enables metrics generator
            generate_native_histograms: both
